# Generated by Django 3.2.25 on 2024-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_orderlineitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
