# Generated by Django 3.2.25 on 2024-07-01 12:55

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country_origin',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
